version: "{branch} {build}"

build:
  verbosity: detailed

build_script:
  - cd HappyBrackets
  - gradlew.bat assemble --info --no-daemon

test_script:
  #- cd HappyBrackets not needed as we are already in the directory following setup
  - gradlew.bat test --info --no-daemon

branches:
  only:
    - master
    - development

cache:
  - C:\Users\appveyor\.gradle

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

matrix:
  fast_finish: true
